version: 2.1
jobs:
  build:
    resource_class: small
    docker:
      - image: cppchriscpp/create-nes-game:<%= it.version %>

        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install dependencies
          command: create-nes-game download-dependencies --assume-yes
      - run: 
          name: Build game
          command: create-nes-game build
<% if (it.game.testProvider !== 'none') { %>
      - run:
          name: Test game
          command: create-nes-game test
<% } %>
      # Store your rom on circleci's servers (warning: artifacts are automatically deleted after 30 days!)
      - store_artifacts:
          path: rom