on: [push]

jobs:
  build_rom:
    runs-on: ubuntu-latest
    # FIXME: use a real version, when we start to publish
    container: cppchriscpp/create-nes-game:latest
    name: Compile rom
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Move things into the spots github CI expects them in
        run: "cp -a /root/. /github/home"
      - name: Install dependencies
        run: create-nes-game download-dependencies --assume-yes
      - name: Build the game
        run: create-nes-game build
<% if (it.game.testProvider !== 'none') { %>
      - name: Start xvfb 
        run: sudo Xvfb :99 -screen 0 1280x1024x24 &
      - name: Run unit tests
        run: DISPLAY=:99 create-nes-game test --debug
      - name: Clean up xvfb
        uses: bcomnes/cleanup-xvfb@v1
<% } %>
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Game Download
          path: rom
