on:
  push:
    tags: 
      - v*

jobs:
  build_tool:
    runs-on: ubuntu-latest
    name: Release new version
    # What this does, in human form: 
    # - Update package.json
    # - build everything
    # - run an integration test
    # - rewrite docs
    # - publish to gh and docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install apt stuff
        run: "sudo apt-get update && sudo apt-get install -y xvfb xdg-utils libxkbcommon-x11-0 libgtk-3-0 libxcursor1 libxss1 libgbm1 libcairo2 libatspi2.0-0 libdbus-glib-1-2 libgtk-3-dev libxt6 fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libpango-1.0-0 libpangocairo-1.0-0 libxcursor1"
      - name: Install all the stuff
        run: npm install
      - name: Set version variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: update package.json with new version
        run: npm version from-git --no-git-tag-version
      - name: Build everything
        run: npm run build-all
      - name: Copy README.md into docs directory to update docs
        run: cp -f README.md docs/README.
      - name: Update version for site
        run: npm run rewrite-site-version

      - name: More debugging junk FIXME KILL DIS
        run: ls -lah /home/runner/.config && pwd && echo $HOME && ls -lah /home/runner/.config/nes-test && ls -lah /home/runner/.config/create-nes-game
      - name: Move a bunch of stuff from our home to root's, since we need root help
        run: sudo cp -r $HOME/.config /root
      - name: Debugging junk, REMOVE ME FIXME
        run: sudo ls -lah /root/.config
      - name: Start xvfb & Run big whale integration tests
        run: sudo Xvfb :99 -screen 0 1280x1024x24 & 
      - name: Run integration tests
        run: sudo node ./test/integration/generate-roms
      - name: Part 2
        run: sudo npx jasmine --config=test/integration/jasmine.json
        #run: sudo Xvfb :99 -screen 0 1280x1024x24 & DISPLAY=:99 npm run full-integration-test
      #  uses: docker://cppchriscpp/create-nes-game:latest
      #  with: 
      #    args: /usr/bin/sh -c "cp -a /root/. /github/home && chmod 777 /github/home && apt-get install -y nodejs npm && DISPLAY=:99 npm run full-integration-test"
      #  run: sudo xvfb-run sudo npm run full-integration-test
      - name: Clean up xvfb
        uses: bcomnes/cleanup-xvfb@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: cppchriscpp/create-nes-game:latest cppchriscpp/create-nes-game:$RELEASE_VERSION

      - name: Release to github
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/*.tar.gz
            dist/*.zip
      - name: "Update github docs in main branch"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated documentation push for release $RELEASE_VERSION
          file_pattern: docs/*
          

